config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "protospaces#index"
  resources :protospaces, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: :create 
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :protospace

  validates :content, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :protospace

  validates :content, presence: true
end

app/models/protospace.rb
class Protospace < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :catch_copy, presence: true
  validates :concept, presence: true  
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true
  validates :profile, presence: true
  validates :occupation, presence: true
  validates :position, presence: true

  has_many :protospaces
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,  :profile, :occupation, :position])
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to protospace_url(@comment.protospace)
    else
      @protospace = @comment.protospace
      @comments = @protospace.comments
      render "protospaces/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, protospace_id: params[:protospace_id])
  end
end

app/controllers/protospaces_controller.rb
class ProtospacesController < ApplicationController
  before_action :set_protospace, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @protospaces = Protospace.includes(:user)
  end

  def new
    @protospace = Protospace.new
  end

  def create
    @protospace = Protospace.new(protospace_params)
    if @protospace.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @comment = Comment.new
    @comments = @protospace.comments
  end

  def edit
  end

  def update
    if @protospace.update(protospace_params)
      redirect_to protospace_path(@protospace)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @protospace.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def protospace_params
    params.require(:protospace).permit(:title, :catch_copy, :concept, :image).merge(user_id: current_user.id)
  end

  def set_protospace
    @protospace = Protospace.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @protospace.user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/protospaces_helper.rb
module ProtospacesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Protospace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__logout %>
              <%= link_to "New Proto", new_protospace_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/protospaces/_form.html.erb
<%= form_with model: protospace, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "プロトタイプの名称" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/protospaces/_protospace.html.erb
<div class="card">
  <%= link_to image_tag(protospace.image, class: :card__img ), protospace_path(protospace) %>
  <div class="card__body">
    <%= link_to protospace.title, protospace_path(protospace), class: :card__title%>
    <p class="card__summary">
      <%= protospace.catch_copy %>
    </p>
    <%= link_to "by #{protospace.user.name}", user_path(protospace.user), class: :card__user %>
  </div>
</div>

app/views/protospaces/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%= render partial: "form", locals: { protospace: @protospace } %>
    </div>
  </div>
</div>

app/views/protospaces/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= link_to "#{current_user.name}さん", user_path(current_user), class: :greeting__link %>
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'protospace', collection: @protospaces %>
    </div>
  </div>
</main>

app/views/protospaces/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
      <%= render partial: "form", locals: { protospace: @protospace } %>
    </div>
  </div>
</div>

app/views/protospaces/show.html.erb
<main class="main">
  <div class="inner">
    <div class="protospace__wrapper">
      <p class="protospace__hedding">
        <%= @protospace.title %>
      </p>
      <%= link_to "by #{@protospace.user.name}", user_path(@protospace.user), class: :protospace__user %>
      <% if current_user == @protospace.user%>
        <div class="protospace__manage">
          <%= link_to "編集する", edit_protospace_path(@protospace), class: :protospace__btn %>
          <%= link_to "削除する", protospace_path(@protospace), data: { turbo_method: :delete }, class: :protospace__btn %>
        </div>
      <% end %>
      <div class="protospace__image">
        <%= image_tag @protospace.image %>
      </div>
      <div class="protospace__body">
        <div class="protospace__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @protospace.catch_copy %>
          </p>
        </div>
        <div class="protospace__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @protospace.concept %>
          </p>
        </div>
      </div>
      <div class="protospace__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@protospace, @comment], local: true do |f|%>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content%>
              <%= link_to "（#{comment.user.name}）", user_path(comment.user), class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/tweets/_message.html.erb
<div class="card">
  <%= link_to image_tag("プロトタイプの画像", class: :card__img ), root_path%>
  <div class="card__body">
    <%= link_to "プロトタイプのタイトル", root_path, class: :card__title%>
    <p class="card__summary">
      <%= "プロトタイプのキャッチコピー" %>
    </p>
    <%= link_to "by プロトタイプの投稿者名", root_path, class: :card__user %>
  </div>
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
</div>

app/views/tweets/index.html.erb
<main class="main">
  <div class="inner">
      <div class="greeting">
         こんにちは、
        <%= link_to "ユーザー名さん", root_path, class: :greeting__link%>
      </div>
    <%# // ログインしているときは上記を表示する %>
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
    </div>
  <%= render partial: 'message', collection: @messages %>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
       <%= "#{@user.name}さんの情報" %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"> <%= @user.name %></td>

          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2">  <%=@user.profile %> </td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2">  <%=@user.occupation %> </td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2">  <%=@user.position %> </td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
         <%=@user.name %>さんのプロトタイプ
      </h2>
      <div class="user__card">
        <%= render partial: 'protospaces/protospace', collection: @user.protospaces %>
      </div>
    </div>
  </div>
</div>